import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { requireAuth } from '@/lib/api-auth'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { response: authResponse } = await requireAuth()
  if (authResponse) return authResponse
  const { id } = await params
  const { data: proposal } = await supabase
    .from('proposals')
    .select('*, line_items:proposal_line_items(*)')
    .eq('id', id)
    .single()

  if (!proposal) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  // Create invoice from proposal
  const dueDate = new Date()
  dueDate.setDate(dueDate.getDate() + 30)

  const { data: invoice, error } = await supabase.from('invoices').insert({
    proposal_id:      proposal.id,
    client_id:        proposal.client_id,
    title:            proposal.title,
    invoice_number:   '',  // auto-generated by trigger
    bill_to_name:     proposal.bill_to_name,
    bill_to_company:  proposal.bill_to_company,
    bill_to_email:    proposal.bill_to_email,
    bill_to_phone:    proposal.bill_to_phone,
    bill_to_address:  proposal.bill_to_address,
    bill_to_city:     proposal.bill_to_city,
    bill_to_state:    proposal.bill_to_state,
    bill_to_zip:      proposal.bill_to_zip,
    subtotal:         proposal.subtotal_equipment + proposal.subtotal_labor,
    tax_rate:         proposal.tax_rate,
    tax_amount:       proposal.tax_amount,
    grand_total:      proposal.grand_total,
    promo_code:       proposal.promo_code ?? null,
    promo_discount:   proposal.promo_discount ?? 0,
    amount_paid:      0,
    issue_date:       new Date().toISOString().split('T')[0],
    due_date:         dueDate.toISOString().split('T')[0],
    rep_name:         proposal.rep_name,
  }).select().single()

  if (error || !invoice) return NextResponse.json({ error: error?.message || 'Failed to create invoice' }, { status: 500 })

  // Copy line items
  if (proposal.line_items?.length) {
    const linePayload = proposal.line_items.map((li: any, i: number) => ({
      invoice_id:  invoice.id,
      section:     li.section,
      sort_order:  i,
      name:        li.name,
      description: li.description,
      qty:         li.qty,
      unit_label:  li.unit_label,
      unit_price:  li.unit_price,
      cost_price:  li.cost_price ?? 0,
      taxable:     li.taxable,
    }))
    await supabase.from('invoice_line_items').insert(linePayload)
  }

  return NextResponse.json({ invoiceId: invoice.id })
}
