import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { requireAuth } from '@/lib/api-auth'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

function advanceDate(date: string, frequency: string): string {
  const d = new Date(date + 'T00:00:00')
  switch (frequency) {
    case 'monthly':   d.setMonth(d.getMonth() + 1); break
    case 'quarterly': d.setMonth(d.getMonth() + 3); break
    case 'annual':    d.setFullYear(d.getFullYear() + 1); break
  }
  return d.toISOString().split('T')[0]
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { response: authResponse } = await requireAuth()
  if (authResponse) return authResponse

  const { id } = await params

  // Fetch recurring schedule
  const { data: schedule } = await supabase
    .from('recurring_invoices')
    .select('*')
    .eq('id', id)
    .single()

  if (!schedule) return NextResponse.json({ error: 'Schedule not found' }, { status: 404 })
  if (!schedule.active) return NextResponse.json({ error: 'Schedule is inactive' }, { status: 400 })

  // Fetch template invoice with line items
  const { data: template } = await supabase
    .from('invoices')
    .select('*, line_items:invoice_line_items(*)')
    .eq('id', schedule.template_invoice_id)
    .single()

  if (!template) return NextResponse.json({ error: 'Template invoice not found' }, { status: 404 })

  // Create new invoice from template
  const dueDate = schedule.next_due_date
  const { data: invoice, error } = await supabase.from('invoices').insert({
    client_id:           template.client_id,
    recurring_invoice_id: schedule.id,
    title:               template.title,
    invoice_number:      '',  // auto-generated by trigger
    bill_to_name:        template.bill_to_name,
    bill_to_company:     template.bill_to_company,
    bill_to_email:       template.bill_to_email,
    bill_to_phone:       template.bill_to_phone,
    bill_to_address:     template.bill_to_address,
    bill_to_city:        template.bill_to_city,
    bill_to_state:       template.bill_to_state,
    bill_to_zip:         template.bill_to_zip,
    subtotal:            template.subtotal,
    tax_rate:            template.tax_rate,
    tax_amount:          template.tax_amount,
    grand_total:         template.grand_total,
    amount_paid:         0,
    issue_date:          new Date().toISOString().split('T')[0],
    due_date:            dueDate,
    rep_name:            template.rep_name,
    notes:               template.notes,
  }).select().single()

  if (error || !invoice) return NextResponse.json({ error: error?.message || 'Failed to create invoice' }, { status: 500 })

  // Copy line items from template
  if (template.line_items?.length) {
    const linePayload = template.line_items.map((li: any, i: number) => ({
      invoice_id:  invoice.id,
      section:     li.section,
      sort_order:  i,
      name:        li.name,
      description: li.description,
      qty:         li.qty,
      unit_label:  li.unit_label,
      unit_price:  li.unit_price,
      cost_price:  li.cost_price ?? 0,
      taxable:     li.taxable,
    }))
    await supabase.from('invoice_line_items').insert(linePayload)
  }

  // Advance schedule
  const nextDue = advanceDate(dueDate, schedule.frequency)
  const updates: Record<string, any> = {
    next_due_date: nextDue,
    last_generated_at: new Date().toISOString(),
  }

  // Deactivate if past end date
  if (schedule.end_date && nextDue > schedule.end_date) {
    updates.active = false
  }

  await supabase.from('recurring_invoices').update(updates).eq('id', id)

  return NextResponse.json({ invoiceId: invoice.id })
}
